version: "3.7"

services:
  keycloak:
    image: ghcr.io/klima-dashboard/keycloak:michendorf
    environment:
      KC_DB: "mariadb"
      KC_DB_USERNAME: root
      KC_HOSTNAME: keycloak.michendorf.klima-daten.de
      KC_DB_URL: 'jdbc:mariadb://mariadb:3306/mysql'
      KC_TRANSACTION_XA_ENABLED: 'false'
    networks:
      public:
      keycloak:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.http.routers.keycloak-michendorf.rule: Host(`keycloak.michendorf.klima-daten.de`)
        traefik.http.routers.keycloak-michendorf.tls: "true"
        traefik.http.routers.keycloak-michendorf.tls.certresolver: default
        traefik.docker.network: public
        traefik.http.services.keycloak-michendorf.loadbalancer.server.port: 8080
        traefik.enable: "true"
    secrets:
      - michendorf-mariadb-keycloak-password
      - michendorf-keycloak-admin-password
    depends_on:
      - mariadb 

  mariadb:
    image: mariadb:10.11
    environment:
      - MARIADB_ROOT_PASSWORD_FILE=/run/secrets/michendorf-mariadb-keycloak-password
    volumes:
      - mariadb-keycloak-data:/var/lib/mysql
    secrets:
      - michendorf-mariadb-keycloak-password
    networks:
      - keycloak

volumes:
  mariadb-keycloak-data:
  keycloak-data:

secrets:
  michendorf-keycloak-admin-password:
    external: true
  michendorf-mariadb-keycloak-password:
    external: true

networks:
  public:
    external: true
  keycloak:
