version: "3.7"

services:
  keycloak:
    image: registry.gitlab.tpwd.de/tpwd/klima-dashboard/keycloak:latest
    environment:
      KEYCLOAK_ADMIN: admin
      DB_VENDOR: "POSTGRES" 
      DB_ADDR: postgres
      DB_PORT: 5432
      DB_USER: postgres
    volumes:
      - keycloak-data:/opt/keycloak/data/h2
    networks:
      public:
      keycloak:
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      labels:
        traefik.http.routers.keycloak.rule: Host(`keycloak.klima-daten.de`)
        traefik.http.routers.keycloak.tls: "true"
        traefik.http.routers.keycloak.tls.certresolver: default
        traefik.docker.network: public
        traefik.http.services.keycloak.loadbalancer.server.port: 8080
        traefik.enable: "true"
    secrets:
      - postgres-password
      - keycloak-admin-password
    depends_on:
      - postgres

  postgres:
    image: postgres:15.1-alpine
    environment:
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgres-password
    volumes:
      - postgres-data:/var/lib/postgresql/data
    secrets:
      - postgres-password

volumes:
  postgres-data:
    external: true
  keycloak-data:
    external: true

secrets:
  keycloak-admin-password:
    external: true
  postgres-password:
    external: true

networks:
  public:
    external: true
  keycloak:
    external: true
