name: Docker Image CI

on:
  push:
    branches: [ release/michendorf ]

jobs:
  build: 
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Login to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - run: >-
          docker build .
          -f Dockerfile
          -t ghcr.io/klima-dashboard/keycloak:michendorf
      - run: docker push ghcr.io/klima-dashboard/keycloak:michendorf
  deploy:
    runs-on: ubuntu-latest
    container: r.planetary-quantum.com/quantum-public/cli:2
    env:
      QUANTUM_USER: ${{ secrets.QUANTUM_USER }}
      QUANTUM_PASSWORD: ${{ secrets.QUANTUM_PASSWORD }}
      QUANTUM_ENDPOINT: "tpwd-klimadashboard"
      QUANTUM_STACK: "michendorf-keycloak"
    steps:
      - uses: actions/checkout@v3
      - name: Deploy to Planetary Quantum
        run: quantum-cli stacks update --create --wait
